# Generated by Django 4.1.3 on 2023-04-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
