# Generated by Django 4.1.3 on 2023-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='autor',
            field=models.CharField(max_length=255),
        ),
    ]
