# Generated by Django 4.1.3 on 2023-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0002_alter_producto_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
